/**
 * Background texture images — black & white mix-in textures
 */
export const BACKGROUND_IMAGES = [
    { value: '', thumb: '', label: 'None' },
    { value: '/backgrounds/birmingham-museums-trust-Bin0C2RtQpI-unsplash.jpg', thumb: '/backgrounds/thumbs/birmingham-museums-trust-Bin0C2RtQpI-unsplash.jpg', label: 'Birmingham Museums' },
    { value: '/backgrounds/leo-chane-Y7YJL3de2zA-unsplash.jpg', thumb: '/backgrounds/thumbs/leo-chane-Y7YJL3de2zA-unsplash.jpg', label: 'Leo Chane' },
    { value: '/backgrounds/omar-flores-lQT_bOWtysE-unsplash.jpg', thumb: '/backgrounds/thumbs/omar-flores-lQT_bOWtysE-unsplash.jpg', label: 'Omar Flores' },
    { value: '/backgrounds/scott-webb-mV9-1XjnM4Y-unsplash.jpg', thumb: '/backgrounds/thumbs/scott-webb-mV9-1XjnM4Y-unsplash.jpg', label: 'Scott Webb' },
    { value: '/backgrounds/sunguk-kim-o9RLeUVowG8-unsplash.jpg', thumb: '/backgrounds/thumbs/sunguk-kim-o9RLeUVowG8-unsplash.jpg', label: 'Sunguk Kim' },
    { value: '/backgrounds/vojtech-bruzek-mCjA1I8SlS8-unsplash.jpg', thumb: '/backgrounds/thumbs/vojtech-bruzek-mCjA1I8SlS8-unsplash.jpg', label: 'Vojtech Bruzek' },
    { value: '/backgrounds/abhay-sachan-I_ZjiAbA_d8-unsplash.jpg', thumb: '/backgrounds/thumbs/abhay-sachan-I_ZjiAbA_d8-unsplash.jpg', label: 'Abhay Sachan' },
    { value: '/backgrounds/anna-magenta-CZMKBCzyGtE-unsplash.jpg', thumb: '/backgrounds/thumbs/anna-magenta-CZMKBCzyGtE-unsplash.jpg', label: 'Anna Magenta' },
    { value: '/backgrounds/annie-spratt-UaIpNXaJORg-unsplash.jpg', thumb: '/backgrounds/thumbs/annie-spratt-UaIpNXaJORg-unsplash.jpg', label: 'Annie Spratt' },
    { value: '/backgrounds/annie-spratt-Y74OXLFiBYI-unsplash.jpg', thumb: '/backgrounds/thumbs/annie-spratt-Y74OXLFiBYI-unsplash.jpg', label: 'Annie Spratt II' },
    { value: '/backgrounds/deep-Ts9_sclEn5k-unsplash.jpg', thumb: '/backgrounds/thumbs/deep-Ts9_sclEn5k-unsplash.jpg', label: 'Deep III' },
    { value: '/backgrounds/grazi-con-2VopZerN9jE-unsplash.jpg', thumb: '/backgrounds/thumbs/grazi-con-2VopZerN9jE-unsplash.jpg', label: 'Grazi Con' },
    { value: '/backgrounds/hammam-fuad-0Kn_nFFPFVo-unsplash.jpg', thumb: '/backgrounds/thumbs/hammam-fuad-0Kn_nFFPFVo-unsplash.jpg', label: 'Hammam Fuad' },
    { value: '/backgrounds/m-umar-farooq-WCQd5-HXdWw-unsplash.jpg', thumb: '/backgrounds/thumbs/m-umar-farooq-WCQd5-HXdWw-unsplash.jpg', label: 'M Umar Farooq' },
    { value: '/backgrounds/martin-sanchez-7ZysQurP1Dg-unsplash.jpg', thumb: '/backgrounds/thumbs/martin-sanchez-7ZysQurP1Dg-unsplash.jpg', label: 'Martin Sanchez' },
    { value: '/backgrounds/public-domain-vectors-VNaBx2Sj-ZQ-unsplash.jpg', thumb: '/backgrounds/thumbs/public-domain-vectors-VNaBx2Sj-ZQ-unsplash.jpg', label: 'Public Domain Vectors III' },
    { value: '/backgrounds/rudra-k-_rGN2nG6Wu0-unsplash.jpg', thumb: '/backgrounds/thumbs/rudra-k-_rGN2nG6Wu0-unsplash.jpg', label: 'Rudra K' },
    { value: '/backgrounds/slimane-kadi-f3tqjx1AW-A-unsplash.jpg', thumb: '/backgrounds/thumbs/slimane-kadi-f3tqjx1AW-A-unsplash.jpg', label: 'Slimane Kadi' },
    { value: '/backgrounds/tasha-kostyuk--GBIkohI2pI-unsplash.jpg', thumb: '/backgrounds/thumbs/tasha-kostyuk--GBIkohI2pI-unsplash.jpg', label: 'Tasha Kostyuk' },
    { value: '/backgrounds/tasha-kostyuk-5Pb0JuMOqbY-unsplash.jpg', thumb: '/backgrounds/thumbs/tasha-kostyuk-5Pb0JuMOqbY-unsplash.jpg', label: 'Tasha Kostyuk II' },
    { value: '/backgrounds/desiignhoud-ai-generated-8229330.jpg', thumb: '/backgrounds/thumbs/desiignhoud-ai-generated-8229330.jpg', label: 'Desiignhoud' },
    { value: '/backgrounds/jennydai-background-6650672.jpg', thumb: '/backgrounds/thumbs/jennydai-background-6650672.jpg', label: 'Jenny Dai' },
    { value: '/backgrounds/madebytin-lemon-8293725.jpg', thumb: '/backgrounds/thumbs/madebytin-lemon-8293725.jpg', label: 'Madebytin Lemon' },
    { value: '/backgrounds/sugeysima-art-6709653.jpg', thumb: '/backgrounds/thumbs/sugeysima-art-6709653.jpg', label: 'Sugeysima Art' },
    { value: '/backgrounds/2768815-background-1462855_1920.jpg', thumb: '/backgrounds/thumbs/2768815-background-1462855_1920.jpg', label: 'Background' },
    { value: '/backgrounds/alexandra_koch-cherries-6294165.jpg', thumb: '/backgrounds/thumbs/alexandra_koch-cherries-6294165.jpg', label: 'Alexandra Koch' },
    { value: '/backgrounds/handdrawn-1.jpg', thumb: '/backgrounds/thumbs/handdrawn-1.jpg', label: 'Hand Drawn I' },
];
